let data = [
	{
		type: 'group',
		name: 'clickables',
		dispose: true,
		sons: [
			{
				type: 'mesh',
				index: 0,
				name: 'Sewage',
				geometry: 'Sewage',
				material: 'Sewage_mat',
				hover: true,
			},
			{
				type: 'mesh',
				index: 1,
				name: 'Truck_smoke',
				geometry: 'Truck_smoke',
				material: 'Truck_Smoke_mat',
				hover: true,
			},
			{
				type: 'group',
				index: 2,
				hover: true,
				sons: [
					{
						type: 'mesh',
						name: 'Trash',
						geometry: 'Trash',
						material: 'Trash_mat',
					},
					{
						type: 'mesh',
						name: 'Trash_throw_1',
						geometry: 'Trash_throw_1',
						material: 'Trash_throw_1_mat',
						position: [16.93, 1.7, 7.29],
						rotation: [-0.67, 0.84, -0.77],
						scale: 0.81,
					},
					{
						type: 'mesh',
						name: 'Trash_throw_2',
						geometry: 'Trash_throw_2',
						material: 'Trash_throw_2_mat',
						position: [6.33, 1.36, 6.47],
						rotation: [0.08, 0.28, -1.18],
						scale: 0.3,
					},
					{
						type: 'mesh',
						name: 'Thrash_throw_3',
						geometry: 'Thrash_throw_3',
						material: 'Trash_throw_3_mat',
						position: [-0.8, 1.52, 3.63],
						rotation: [0.11, 0.17, -0.08],
						scale: 0.71,
					},
				],
			},
			{
				type: 'group',
				index: 3,
				hover: true,
				sons: [
					{
						type: 'mesh',
						name: 'Chimney_smoke',
						geometry: 'Chimney_smoke',
						material: 'Chimney_Smoke_mat',
						wobbleMaterial: {
							metalness: 0.3,
							map: 'Chimney_Smoke_mat',
							factor: 0.02,
							speed: 1,
							transparent: true,
						},
					},
					{
						type: 'mesh',
						name: 'Chimneys',
						geometry: 'Chimneys',
						material: 'Chimney_mat',
					},
				],
			},
		],
	},
	{
		type: 'group',
		name: 'statics',
		dispose: true,
		sons: [
			{
				type: 'mesh',
				name: 'Blue_car',
				geometry: 'Blue_car',
				material: 'Blue_car_mat',
				position: [-0.19, 1.1, 2.86],
				wobbleMaterial: {
					metalness: 0.3,
					map: 'Blue_car_mat',
					factor: 0.025,
					speed: 40,
				},
			},
			{
				type: 'mesh',
				name: 'Blue_truck',
				geometry: 'Blue_truck',
				material: 'Blue_Truck_mat',
				position: [10.63, 1.28, 2.05],
				wobbleMaterial: {
					metalness: 0.125,
					map: 'Blue_Truck_mat',
					factor: 0.015,
					speed: 50,
				},
			},
			{
				type: 'mesh',
				name: 'Green_car',
				geometry: 'Green_car',
				material: 'Green_car_mat',
				position: [18.03, 1.08, 5.62],
				wobbleMaterial: {
					metalness: 0.3,
					map: 'Green_car_mat',
					factor: 0.025,
					speed: 60,
				},
			},
			{
				type: 'mesh',
				name: 'Red_truck',
				geometry: 'Red_truck',
				material: 'Red_truck_mat',
				position: [-5.69, 1.27, 5.7],
				wobbleMaterial: {
					metalness: 0.3,
					map: 'Red_truck_mat',
					factor: 0.015,
					speed: 50,
				},
			},
			{
				type: 'mesh',
				name: 'Red_car',
				geometry: 'Red_car',
				material: 'Red_car_mat',
				position: [7.59, 1.01, 6.04],
				wobbleMaterial: {
					metalness: 0.3,
					map: 'Red_car_mat',
					factor: 0.025,
					speed: 40,
				},
			},
			{
				type: 'mesh',
				name: 'Bushes',
				geometry: 'Bushes',
				material: 'Bushes_mat',
			},
			{
				type: 'mesh',
				name: 'Scenery',
				geometry: 'Scenery',
				material: 'Scenery_mat',
				standardMaterial: {
					metalness: 0.3,
					map: 'Scenery_mat',
				},
			},
			{
				type: 'mesh',
				name: 'River',
				geometry: 'River',
				material: 'River_mat',
			},
		],
	},
];

export { data };
